# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'install sdk'
  inputs:
    packageType: 'sdk'
    version: '6.x'

- task: DotNetCoreCLI@2
  displayName: 'restore packages'
  inputs:
    command: 'restore'
    projects: 'pipelines-dotnet-core.csproj'

- task: DotNetCoreCLI@2
  displayName: 'build app'
  inputs:
    command: 'build'
    projects: 'pipelines-dotnet-core.csproj'
    arguments: '--configuration $(buildConfiguration)'


- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

